apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: spokes-subscription
  namespace: acm-subscriptions
  labels:
    app: spokes-subscription
  annotations:
    apps.open-cluster-management.io/git-path: spoke_clusters
    apps.open-cluster-management.io/git-branch: stable/4.7
spec:
  channel: acm-subscriptions/acm-subscription 
  placement:
    local: true
