apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: cu-subscription
  namespace: cu-subscriptions
  labels:
    app: cu-subscription
  annotations:
    apps.open-cluster-management.io/git-path: manifests/function/cu
    apps.open-cluster-management.io/git-branch: stable/4.7
spec:
  channel: cu-subscriptions/cu-subscription 
  placement:
    local: true
