apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
  - 00_endpoint_crd.yaml
  - 01_namespace.yaml
  - 02_service_account.yaml
  - 03_klusterlet_clusterrole.yaml
  - 04_aggregate_clusterrole.yaml
  - 05_klusterlet_clusterrolebinding.yaml
  - 06_klusterlet_deployment.yaml
  - 07_klusterlet.yaml

secretGenerator:
- name: bootstrap-hub-kubeconfig
  namespace: open-cluster-management-agent
  files:
    - kubeconfig
  type: Opaque


